filegroup(
    name = "echo-boostd-service",
    srcs = ["echo-boostd.service"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "echo-grpcd-service",
    srcs = ["echo-grpcd.service"],
    visibility = ["//visibility:public"],
)
